"""Prompt templates for mood-based artist filtering workflows."""


def get_artist_filtering_prompt(mood_prompt: str, mood_interpretation: str, artists_summary: str) -> str:
    """Build the LLM prompt used to select artists that match a requested mood.

    Args:
        mood_prompt: Original mood description provided by the user.
        mood_interpretation: Normalized mood analysis generated by the analyzer agent.
        artists_summary: Enumerated list of candidate artists with supporting details.

    Returns:
        A formatted conversational prompt instructing the model to choose artists and
        explain the selection in JSON form.
    """
    return f"""You are a music curator selecting artists that match a specific mood.

**User's Mood**: "{mood_prompt}"

**Mood Analysis**: {mood_interpretation}

**Available Artists**:
{artists_summary}

**Task**: Select 12-20 artists from the list that best match this mood for MAXIMUM DIVERSITY. Consider:
1. Genre compatibility with the mood
2. Artist style and vibe
3. IMPORTANT: Mix of popular and lesser-known artists for variety
4. Overall cohesion with the requested mood
5. Prefer MORE artists over fewer for playlist diversity

Respond in JSON format:
{{
  "selected_artist_indices": [1, 3, 5, ...],
  "reasoning": "Brief explanation of why these artists fit the mood"
}}

Select artist indices (numbers from the list above). Aim for 12-20 artists for best diversity."""
